name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

jobs:
  build-prerelease:
    uses: ./.github/workflows/cd-template.yml
    with:
      APP_NAME: watcher
      DRAFT: true
    secrets: inherit
